In [2]:
'''
#在数据集上进行多类别分类，主要可以使用SVC，NuSVC和LinearSVC这三个类!!!!!!!

SVC参数解释
（1）C: 目标函数的惩罚系数C，用来平衡分类间隔margin和错分样本的，default C = 1.0；
（2）kernel：参数选择有RBF, Linear, Poly, Sigmoid, 默认的是"RBF";
（3）degree：if you choose 'Poly' in param 2, this is effective, degree决定了多项式的最高次幂；
（4）gamma：核函数的系数('Poly', 'RBF' and 'Sigmoid'), 默认是gamma = 1 / n_features;
（5）coef0：核函数中的独立项，'RBF' and 'Poly'有效；
（6）probablity: 可能性估计是否使用(true or false)；
（7）shrinking：是否进行启发式；
（8）tol（default = 1e - 3）: svm结束标准的精度;
（9）cache_size: 制定训练所需要的内存（以MB为单位）；
（10）class_weight: 每个类所占据的权重，不同的类设置不同的惩罚参数C, 缺省的话自适应；
（11）verbose: 跟多线程有关，不大明白啥意思具体；
（12）max_iter: 最大迭代次数，default = 1， if max_iter = -1, no limited;
（13）decision_function_shape ： ‘ovo’ 一对一, ‘ovr’ 一对多  or None 无, default=None
（14）random_state ：用于概率估计的数据重排时的伪随机数生成器的种子。
 ps：7,8,9一般不考虑。
 
'''



from sklearn import svm
import numpy as np
#二分类，以svc介绍（NuSvc类似）
x= np.array([[-1,-1],[-2,-1],[2,1]])
y = np.array([1,1,2])
clf = svm.SVC(gamma='auto')
clf.fit(x, y)
#以上代码执行完后，已经训练好模型

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [3]:

#这里新输入X进行预测！！！！！！！！！！
clf.predict([[-2., -1.]])

array([1])

In [4]:

#进行查看是哪些在支持SVM，即get support vectors
clf.support_vectors_

array([[-1., -1.],
       [-2., -1.],
       [ 2.,  1.]])

In [5]:

# 获得每个类的支持向量数，get number of support vectors for each class
clf.n_support_ 

array([2, 1])

In [6]:

#get indices of support vectors,获得支持向量的索引
clf.support_ 

array([0, 1, 2])

In [7]:
'''
 #下面的警告，是由于版本问题，可以不予理会！！！！！！
 在0.22版本中，gamma的默认值将从“auto”更改为“scale”，以更好地考虑未缩放的功能。 将gamma明确设置为“auto”或“scale”以避免此警告。

'''
# 多类别分类
X1 = [[0], [1], [2], [3]]
Y1 = [0, 1, 2, 3]
####一对一
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X1, Y1) 
dec = clf.decision_function([[1]])
print(dec.shape[1])
print(dec)  #注意理解6/4下面的输出维数6
####一对多
clf1 = svm.SVC(decision_function_shape='ovr')
clf1.fit(X1, Y1) 
dec1 = clf1.decision_function([[1]])
print(dec1.shape[1])
print(dec1)   #注意理解6/4下面的输出维数4
clf1.predict([[2]])  #新样本预测

6
[[-0.63212056  0.          0.3495638   0.63212056  0.98168436  0.3495638 ]]
4
[[ 1.9370957   3.5         0.9370957  -0.37419139]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([2])

LinearSVC是对支持向量分类的另一种实现，使用了线性核。注意LinearSVC不接受关键字kernel，因为核被预设为是线性的
可以理解为使用的核函数是”linear“


In [8]:
#也是一对多
lin_clf = svm.LinearSVC()
lin_clf.fit(X1, Y1)
#注意下面输出与上面SVC输出训练函数的参数的不同之处

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [9]:
dec = lin_clf.decision_function([[1]])   # LinearSVC也可以直接用“合并”，与SVC进行对比理解！！！
print(dec)   #返回的是样本距离超平面的距离,有4个样本，即返回4维，注意与上面进行对比理解！！！！！
dec.shape[1]



[[-0.54545708 -0.37606615 -0.47861365 -0.58122661]]


4

In [10]:
lin_clf.predict([[9]])  # 输入新样本进行预测

array([3])

In [1]:
from sklearn import datasets